services:
  postgres:
    image: postgres:15
    restart: always
    env_file: 
      - .env  
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  # backend:
  #   build: ./english-learning-be
  #   env_file:
  #     - ./english-learning-be/.env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./english-learning-be:/usr/src/app
  #   command: npm run start:dev

volumes:
  postgres_data:
  redis_data:
